# Generated by Django 2.2.1 on 2019-05-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime_buss', models.DateTimeField()),
                ('buyer', models.IntegerField()),
                ('seller', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qtd', models.IntegerField()),
                ('tot_qtd', models.IntegerField()),
                ('tot_buss', models.IntegerField()),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mining.Active')),
            ],
        ),
    ]
