# Generated by Django 2.2.1 on 2019-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_auto_20190507_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
