# Generated by Django 2.2.1 on 2019-05-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_auto_20190508_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='time_stamp',
            new_name='datetime_buss',
        ),
    ]
