# Generated by Django 2.2.1 on 2019-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_auto_20190508_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='datetime_buss',
            field=models.DateTimeField(),
        ),
    ]
